In [1]:
import pandas as pd

In [3]:
df = pd.read_json("../data/raw/sabbar_2026-09-10.json")
df

,url,id,title,company,industries,salary,max_salary,currency,salary_frequency,contract_type,...,city,district,address,country,postal_code,created_date,job_status,is_new,source,description
0,https://sabbar.com/en/jobs/c-jeddah-r-%D8%A8%D...,e5e16dbc-d4d3-4529-bcf6-fe9e1d66f100,بائع أدوات وأجهزة منزلية,اكسترا,Retail,NaN,NaN,SAR,MONTHLY,PARTTIME,...,Jeddah,,Jeddah,Saudi Arabia,NaN,1.788993e+09,OPEN,1.0,IN_PLATFORM,<p>نبحث عن بائع متحمس وملتزم للانضمام إلى فريق...
1,https://sabbar.com/en/jobs/r-%D9%85%D8%B4%D8%B...,8b8cf5ae-c9fd-4d55-bc47-6eaad55aceaf,مشرف تطوير أعمال,Sedan سيدان,Information,2500.0,3500.0,SAR,MONTHLY,PARTTIME,...,,,Saudi Arabia,Saudi Arabia,19211.0,1.788990e+09,OPEN,1.0,IN_PLATFORM,<p>نبحث عن مشرف تطوير أعمال متحمس للانضمام إلى...
2,https://sabbar.com/en/jobs/c-jeddah-r-%D9%85%D...,219cac5e-d6f3-43f3-92df-c03d29f8597c,موظفة استقبال,قهوان ونسمار,F&B,NaN,NaN,SAR,MONTHLY,PARTTIME,...,Jeddah,An Naim,"An Naim, Jeddah",Saudi Arabia,23621.0,1.788991e+09,OPEN,1.0,IN_PLATFORM,<p>موضفه استقبال ل مطعم يفضل وجود خبره</p>
3,https://sabbar.com/en/jobs/c-riyadh-r-%D9%85%D...,7dc458d5-6338-4987-897a-1a6cb1655920,مقدم طعام (ويتر),شركة مهام الغذاء,F&B,NaN,NaN,SAR,MONTHLY,FULLTIME,...,Riyadh,Al Olaya,"Al Olaya, Riyadh",Saudi Arabia,12212.0,1.788988e+09,OPEN,1.0,IN_PLATFORM,<p>نبحث عن مقدمي طعام (ويتر) متحمسين للانضمام ...
4,https://sabbar.com/en/jobs/c-riyadh-r-team-lea...,4a000307-0a53-4d37-bfff-26853f230cca,Team Leader,مؤسسة عصفور التجارية,Retail,NaN,NaN,SAR,MONTHLY,FULLTIME,...,Riyadh,Al Sulaimaniyah,"Al Sulaimaniyah, Riyadh",Saudi Arabia,12243.0,1.788988e+09,OPEN,1.0,IN_PLATFORM,<p>Sweet Shop Supervisor &amp; Cashier<br/>​Ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15673,https://sabbar.com/en/jobs/c-riyadh-r-sales-re...,1d775198-8f8a-40fc-ad0c-a5f71727e0f7,Sales Representative,Deraah Perfumes | درعه للعطور,Retail,5000.0,NaN,SAR,MONTHLY,FULLTIME,...,Hawtat Bani Tamim,Riyadh Province,"Riyadh Province, Hawtat Bani Tamim",Saudi Arabia,16511.0,1.763892e+09,OPEN,0.0,IN_PLATFORM,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...
15674,https://sabbar.com/en/jobs/c-riyadh-r-sales-re...,1d775198-8f8a-40fc-ad0c-a5f71727e0f7,Sales Representative,Deraah Perfumes | درعه للعطور,Retail,5000.0,NaN,SAR,MONTHLY,FULLTIME,...,Hawtat Bani Tamim,Riyadh Province,"Riyadh Province, Hawtat Bani Tamim",Saudi Arabia,16511.0,1.763892e+09,OPEN,0.0,IN_PLATFORM,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...
15675,https://sabbar.com/en/jobs/c-hawtat-bani%20tam...,1d775198-8f8a-40fc-ad0c-a5f71727e0f7,Sales Representative,Deraah Perfumes | درعه للعطور,Retail,5000.0,NaN,SAR,MONTHLY,FULLTIME,...,Hawtat Bani Tamim,Riyadh Province,"Riyadh Province, Hawtat Bani Tamim",Saudi Arabia,16511.0,1.763892e+09,OPEN,0.0,IN_PLATFORM,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...
15676,https://sabbar.com/en/jobs/c-riyadh-r-sales-re...,1d775198-8f8a-40fc-ad0c-a5f71727e0f7,Sales Representative,Deraah Perfumes | درعه للعطور,Retail,5000.0,NaN,SAR,MONTHLY,FULLTIME,...,Hawtat Bani Tamim,Riyadh Province,"Riyadh Province, Hawtat Bani Tamim",Saudi Arabia,16511.0,1.763892e+09,OPEN,0.0,IN_PLATFORM,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...
15677,https://sabbar.com/en/jobs/c-riyadh-r-sales-re...,1d775198-8f8a-40fc-ad0c-a5f71727e0f7,Sales Representative,Deraah Perfumes | درعه للعطور,Retail,5000.0,NaN,SAR,MONTHLY,FULLTIME,...,Hawtat Bani Tamim,Riyadh Province,"Riyadh Province, Hawtat Bani Tamim",Saudi Arabia,16511.0,1.763892e+09,OPEN,0.0,IN_PLATFORM,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...

In [5]:
df.shape

(15678, 30)

In [8]:
df.duplicated(subset=["url"]).sum()

np.int64(1023)

In [9]:
df = df.drop_duplicates(subset=["url"]).reset_index(drop=True)

In [10]:
df.shape

(14655, 30)

In [11]:
profile = pd.DataFrame({
    "dtype": df.dtypes,
    "nulls": df.isnull().sum(),
    "null_pct": (df.isnull().mean()*100).round(1),
    "unique": df.nunique(),
})
profile

                        dtype  nulls  null_pct  unique
url                       str      0       0.0   14655
id                        str      0       0.0    8307
title                     str      1       0.0    3857
company                   str      0       0.0    3479
industries                str      0       0.0     174
salary                float64   9620      65.6     129
max_salary            float64  11718      80.0     133
currency                  str      1       0.0       1
salary_frequency          str      1       0.0       3
contract_type             str      1       0.0       4
workplace_type            str      1       0.0       3
experience_years          str      1       0.0       4
requires_experience   float64      1       0.0       2
requires_english      float64      1       0.0       2
english_proficiency       str  13895      94.8       3
requires_gosi         float64      1       0.0       2
requires_health_card  float64      1       0.0       1
gender                    str      1       0.0       3
saudis_only           float64      1       0.0       2
females_only_env      float64      1       0.0       2
city                      str      1       0.0     111
district                  str  12893      88.0     257
address                   str      1       0.0     427
country                   str      1       0.0       1
postal_code           float64   3274      22.3     369
created_date          float64      1       0.0    7751
job_status                str      1       0.0       2
is_new                float64      1       0.0       2
source                    str      1       0.0       2
description               str      0       0.0     875

In [12]:
df_clean = df.copy()

In [13]:
df_clean["created_date"].dropna().head()

0    1.788993e+09
1    1.788990e+09
2    1.788991e+09
3    1.788988e+09
4    1.788988e+09
Name: created_date, dtype: float64

In [14]:
df_clean["posted_date"] = pd.to_datetime(
    df_clean["created_date"], unit="s"
).dt.strftime("%Y-%m-%d")

df_clean[["created_date", "posted_date"]].head()

   created_date posted_date
0  1.788993e+09  2026-09-09
1  1.788990e+09  2026-09-09
2  1.788991e+09  2026-09-09
3  1.788988e+09  2026-09-09
4  1.788988e+09  2026-09-09

In [15]:
df_clean.head(20)

,url,id,title,company,industries,salary,max_salary,currency,salary_frequency,contract_type,...,district,address,country,postal_code,created_date,job_status,is_new,source,description,posted_date
0,https://sabbar.com/en/jobs/c-jeddah-r-%D8%A8%D...,e5e16dbc-d4d3-4529-bcf6-fe9e1d66f100,بائع أدوات وأجهزة منزلية,اكسترا,Retail,NaN,NaN,SAR,MONTHLY,PARTTIME,...,,Jeddah,Saudi Arabia,NaN,1.788993e+09,OPEN,1.0,IN_PLATFORM,<p>نبحث عن بائع متحمس وملتزم للانضمام إلى فريق...,2026-09-09
1,https://sabbar.com/en/jobs/r-%D9%85%D8%B4%D8%B...,8b8cf5ae-c9fd-4d55-bc47-6eaad55aceaf,مشرف تطوير أعمال,Sedan سيدان,Information,2500.0,3500.0,SAR,MONTHLY,PARTTIME,...,,Saudi Arabia,Saudi Arabia,19211.0,1.788990e+09,OPEN,1.0,IN_PLATFORM,<p>نبحث عن مشرف تطوير أعمال متحمس للانضمام إلى...,2026-09-09
2,https://sabbar.com/en/jobs/c-jeddah-r-%D9%85%D...,219cac5e-d6f3-43f3-92df-c03d29f8597c,موظفة استقبال,قهوان ونسمار,F&B,NaN,NaN,SAR,MONTHLY,PARTTIME,...,An Naim,"An Naim, Jeddah",Saudi Arabia,23621.0,1.788991e+09,OPEN,1.0,IN_PLATFORM,<p>موضفه استقبال ل مطعم يفضل وجود خبره</p>,2026-09-09
3,https://sabbar.com/en/jobs/c-riyadh-r-%D9%85%D...,7dc458d5-6338-4987-897a-1a6cb1655920,مقدم طعام (ويتر),شركة مهام الغذاء,F&B,NaN,NaN,SAR,MONTHLY,FULLTIME,...,Al Olaya,"Al Olaya, Riyadh",Saudi Arabia,12212.0,1.788988e+09,OPEN,1.0,IN_PLATFORM,<p>نبحث عن مقدمي طعام (ويتر) متحمسين للانضمام ...,2026-09-09
4,https://sabbar.com/en/jobs/c-riyadh-r-team-lea...,4a000307-0a53-4d37-bfff-26853f230cca,Team Leader,مؤسسة عصفور التجارية,Retail,NaN,NaN,SAR,MONTHLY,FULLTIME,...,Al Sulaimaniyah,"Al Sulaimaniyah, Riyadh",Saudi Arabia,12243.0,1.788988e+09,OPEN,1.0,IN_PLATFORM,<p>Sweet Shop Supervisor &amp; Cashier<br/>​Ma...,2026-09-09
5,https://sabbar.com/en/jobs/c-riyadh-r-demi-che...,c183089b-8786-4530-ad41-105d981301a0,Demi Chef de Partie,Mr Smashy,F&B,70.0,90.0,SAR,HOURLY,PARTTIME,...,Al Narjis,"Al Narjis, Riyadh",Saudi Arabia,13328.0,1.788987e+09,OPEN,1.0,IN_PLATFORM,<p>We are seeking a skilled and passionate Dem...,2026-09-09
6,https://sabbar.com/en/jobs/c-riyadh-r-hr-assis...,0871398c-b76d-42cb-8afa-2c30cce2b1e7,HR Assistant,lite,"Information, Finance & Accounting",NaN,NaN,SAR,MONTHLY,FULLTIME,...,Al Nafel,"Al Nafel, Riyadh",Saudi Arabia,13312.0,1.788986e+09,OPEN,1.0,IN_PLATFORM,$2c,2026-09-09
7,https://sabbar.com/en/jobs/r-%D9%85%D8%B3%D8%A...,bf33788a-eafa-49c9-815b-b90d0beb45a4,مسؤول حملات سوشيال ميديا,Blarkperfume,Manufacturing,800.0,1000.0,SAR,MONTHLY,SEASONAL,...,,Saudi Arabia,Saudi Arabia,19211.0,1.788986e+09,OPEN,1.0,IN_PLATFORM,"<p class=""ql-direction-rtl"">نبحث عن شخص خبير و...",2026-09-09
8,https://sabbar.com/en/jobs/c-jeddah-r-personal...,4445507a-7772-4025-96a3-e37e4d98eaa4,Personal Assistant,شركة نجوم المستقبل القابضة,Construction,5000.0,8000.0,SAR,MONTHLY,FULLTIME,...,Al Basatin,"Al Basatin, Jeddah",Saudi Arabia,23718.0,1.788984e+09,OPEN,1.0,IN_PLATFORM,نبحث عن مساعد شخصي يتمتع بمهارات تنظيمية عالية...,2026-09-09
9,https://sabbar.com/en/jobs/c-dammam-r-%D9%85%D...,e077bab9-d228-4d6f-9286-1b1be9a37dc4,مشرف تطوير أعمال,نجد العقارية,"Real Estate, Finance & Accounting, Construction",NaN,NaN,SAR,MONTHLY,FULLTIME,...,,Dammam,Saudi Arabia,NaN,1.788983e+09,OPEN,1.0,IN_PLATFORM,<p>نبحث عن مشرف تطوير أعمال يتمتع برؤية استرات...,2026-09-09
10,https://sabbar.com/en/jobs/c-jeddah-r-general-...,4d632906-1ee4-40d8-8d79-05d04e8bde55,General Accountant,D Company,"Professional Services, Manufacturing, Retail",4000.0,NaN,SAR,MONTHLY,FULLTIME,...,Abhur Ash Shamaliyah,"Abhur Ash Shamaliyah, Jeddah",Saudi Arabia,23815.0,1.788980e+09,OPEN,1.0,IN_PLATFORM,<p>seeking an accountant with 5+ years of expe...,2026-09-09
11,https://sabbar.com/en/jobs/c-makkah-r-%D8%A8%D...,0213925c-2ef7-467f-9fc1-595a698d8164,بائع مستحضرات وأدوات تجميل ومكياج,Danube | الدانوب,Retail,4500.0,NaN,SAR,MONTHLY,FULLTIME,...,Al Awali,"Al Awali, Makkah",Saudi Arabia,24251.0,1.788982e+09,OPEN,1.0,IN_PLATFORM,<p>نبحث عن بائع متحمس وشغوف بمستحضرات وأدوات ا...,2026-09-09
12,https://sabbar.com/en/jobs/c-riyadh-r-%D9%85%D...,ad1b9bb8-8141-4fb2-a8b0-b2b1d0eb9272,محصل ديون,شركة ريكافا,"Finance & Accounting, Professional Services, R...",NaN,NaN,SAR,MONTHLY,FULLTIME,...,Al Suwaidi,"Al Suwaidi, Riyadh",Saudi Arabia,12786.0,1.788979e+09,OPEN,1.0,IN_PLATFORM,<p>تعلن الشركة عن توفر شاغر وظيفي بمسى محصل دي...,2026-09-09
13,https://sabbar.com/en/jobs/c-riyadh-r-tailor/i...,9e547a09-a954-419b-8f7e-24c958000281,Tailor,شركة تسوى الاعمال,Professional Services,4000.0,4100.0,SAR,MONTHLY,FULLTIME,...,King Abdullah,"King Abdullah, Riyadh",Saudi Arabia,12411.0,1.788978e+09,OPEN,1.0,IN_PLATFORM,نبحث عن خياط ماهر للانضمام إلى فريقنا، يمتلك خ...,2026-09-09
14,https://sabbar.com/en/jobs/c-jeddah-r-pharmaci...,199305fb-4702-4272-9750-b9cdb99b56f6,Pharmacist,شركة دار العائلة الطبية,Professional Services,7000.0,NaN,SAR,MONTHLY,FULLTIME,...,As Salamah,"As Salamah, Jeddah",Saudi Arabia,23436.0,1.788977e+09,OPEN,1.0,IN_PLATFORM,"<p data-start=""135"" data-end=""183"" class=""PDq2...",2026-09-09
15,https://sabbar.com/en/jobs/c-dammam-r-%D9%85%D...,0fa7d9f4-d63d-4458-9c27-478f6a4ab1b2,موظف موارد بشرية,TPG,"Construction, Real Estate, F&B",NaN,NaN,SAR,MONTHLY,FULLTIME,...,Ar Rawdah,"Ar Rawdah, Dammam",Saudi Arabia,32256.0,1.788975e+09,OPEN,1.0,IN_PLATFORM,$2c,2026-09-09
16,https://sabbar.com/en/jobs/c-riyadh-r-%D9%85%D...,23a0ad7a-d677-4e2d-a982-19a4d9dec1c6,محاسب عام,شركة تسوى الاعمال,Professional Services,4500.0,5850.0,SAR,MONTHLY,FULLTIME,...,Al Jazeerah,"Al Jazeerah, Riyadh",Saudi Arabia,14261.0,1.788974e+09,OPEN,1.0,IN_PLATFORM,<p>مطلوب محاسب عام للعمل في شركة رائدة بمجال ا...,2026-09-09
17,https://sabbar.com/en/jobs/c-riyadh-r-operatio...,66fa56a7-da74-4e9e-a616-1d2a2f81f420,Operation Manager,ون ورث 01WORTH I,"Retail, Construction",8000.0,10000.0,SAR,MONTHLY,FULLTIME,...,Al Muhammadiyah,"Al Muhammadiyah, Riyadh",Saudi Arabia,12364.0,1.788972e+09,OPEN,1.0,IN_PLATFORM,<p>We are looking for an experienced Operation...,2026-09-09
18,https://sabbar.com/en/jobs/c-jeddah-r-%D9%85%D...,e4889232-e75c-4f57-8eda-fbbc3e5bc409,مدير حركة سيارات,FASTEST LINE,Transportation & Logistics,6000.0,8000.0,SAR,MONTHLY,FULLTIME,...,Al Muhammadiyah,"Al Muhammadiyah, Jeddah",Saudi Arabia,23623.0,1.788970e+09,OPEN,1.0,IN_PLATFORM,"<li data-section-id=""15nu33i"" data-start=""1458...",2026-09-09
19,https://sabbar.com/en/jobs/c-riyadh-r-graphic-...,693d44d7-7f88-4b2f-8bdf-816f8dc66ead,Graphic Designer,معهد الإمداد العالي للتدريب,Education,4000.0,4500.0,SAR,MONTHLY,FULLTIME,...,Al Nadwah,"Al Nadwah, Riyadh",Saudi Arabia,14816.0,1.788968e+09,OPEN,1.0,IN_PLATFORM,$2c,2026-09-09

In [17]:
df_clean.duplicated().sum()

np.int64(0)

In [18]:
df_clean = df_clean.rename(columns={
    "url": "job_url",
    "title": "job_title",
    "company": "company_name",
    "description": "job_description",
    "contract_type": "employment_type",
    "workplace_type": "work_mode",
    "experience_years": "experience_needed",
})

df_clean["source"] = "sabbar"
df_clean["city"] = df_clean["city"].replace(r"^\s*$", None, regex=True)

# دمج الراتب لنص (حسب الـSchema)
df_clean["salary"] = df_clean.apply(
    lambda r: f"{int(r['salary'])}-{int(r['max_salary'])}"
    if pd.notna(r["salary"]) and pd.notna(r["max_salary"])
    else (str(int(r["salary"])) if pd.notna(r["salary"]) else None),
    axis=1,
)


for col in ["career_level", "qualification_required", "skills",
            "estimated_salary", "collected_at"]:
    df_clean[col] = None


schema_cols = [
    "source", "job_title", "company_name", "job_description", "job_url",
    "country", "city", "work_mode", "employment_type", "career_level",
    "experience_needed", "qualification_required", "skills",
    "salary", "estimated_salary", "posted_date", "collected_at",
]
df_clean = df_clean[schema_cols]
df_clean.head()

,source,job_title,company_name,job_description,job_url,country,city,work_mode,employment_type,career_level,experience_needed,qualification_required,skills,salary,estimated_salary,posted_date,collected_at
0,sabbar,بائع أدوات وأجهزة منزلية,اكسترا,<p>نبحث عن بائع متحمس وملتزم للانضمام إلى فريق...,https://sabbar.com/en/jobs/c-jeddah-r-%D8%A8%D...,Saudi Arabia,Jeddah,REMOTE,PARTTIME,None,0-1,None,None,NaN,None,2026-09-09,None
1,sabbar,مشرف تطوير أعمال,Sedan سيدان,<p>نبحث عن مشرف تطوير أعمال متحمس للانضمام إلى...,https://sabbar.com/en/jobs/r-%D9%85%D8%B4%D8%B...,Saudi Arabia,NaN,REMOTE,PARTTIME,None,2-5,None,None,2500-3500,None,2026-09-09,None
2,sabbar,موظفة استقبال,قهوان ونسمار,<p>موضفه استقبال ل مطعم يفضل وجود خبره</p>,https://sabbar.com/en/jobs/c-jeddah-r-%D9%85%D...,Saudi Arabia,Jeddah,ON_SITE,PARTTIME,None,2-5,None,None,NaN,None,2026-09-09,None
3,sabbar,مقدم طعام (ويتر),شركة مهام الغذاء,<p>نبحث عن مقدمي طعام (ويتر) متحمسين للانضمام ...,https://sabbar.com/en/jobs/c-riyadh-r-%D9%85%D...,Saudi Arabia,Riyadh,ON_SITE,FULLTIME,None,2-5,None,None,NaN,None,2026-09-09,None
4,sabbar,Team Leader,مؤسسة عصفور التجارية,<p>Sweet Shop Supervisor &amp; Cashier<br/>​Ma...,https://sabbar.com/en/jobs/c-riyadh-r-team-lea...,Saudi Arabia,Riyadh,ON_SITE,FULLTIME,None,2-5,None,None,NaN,None,2026-09-09,None

In [19]:
df_clean

,source,job_title,company_name,job_description,job_url,country,city,work_mode,employment_type,career_level,experience_needed,qualification_required,skills,salary,estimated_salary,posted_date,collected_at
0,sabbar,بائع أدوات وأجهزة منزلية,اكسترا,<p>نبحث عن بائع متحمس وملتزم للانضمام إلى فريق...,https://sabbar.com/en/jobs/c-jeddah-r-%D8%A8%D...,Saudi Arabia,Jeddah,REMOTE,PARTTIME,None,0-1,None,None,NaN,None,2026-09-09,None
1,sabbar,مشرف تطوير أعمال,Sedan سيدان,<p>نبحث عن مشرف تطوير أعمال متحمس للانضمام إلى...,https://sabbar.com/en/jobs/r-%D9%85%D8%B4%D8%B...,Saudi Arabia,NaN,REMOTE,PARTTIME,None,2-5,None,None,2500-3500,None,2026-09-09,None
2,sabbar,موظفة استقبال,قهوان ونسمار,<p>موضفه استقبال ل مطعم يفضل وجود خبره</p>,https://sabbar.com/en/jobs/c-jeddah-r-%D9%85%D...,Saudi Arabia,Jeddah,ON_SITE,PARTTIME,None,2-5,None,None,NaN,None,2026-09-09,None
3,sabbar,مقدم طعام (ويتر),شركة مهام الغذاء,<p>نبحث عن مقدمي طعام (ويتر) متحمسين للانضمام ...,https://sabbar.com/en/jobs/c-riyadh-r-%D9%85%D...,Saudi Arabia,Riyadh,ON_SITE,FULLTIME,None,2-5,None,None,NaN,None,2026-09-09,None
4,sabbar,Team Leader,مؤسسة عصفور التجارية,<p>Sweet Shop Supervisor &amp; Cashier<br/>​Ma...,https://sabbar.com/en/jobs/c-riyadh-r-team-lea...,Saudi Arabia,Riyadh,ON_SITE,FULLTIME,None,2-5,None,None,NaN,None,2026-09-09,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14650,sabbar,Seller,تطوير | Tatwir,<div>توظيف فوري </div><div>كمزود/ة خدمة مبيعات...,https://sabbar.com/en/jobs/c-khamis-mushayt-r-...,Saudi Arabia,Khamis Mushayt,ON_SITE,FULLTIME,None,2-5,None,None,4000-8500,None,2025-11-24,None
14651,sabbar,Sales Representative,Deraah Perfumes | درعه للعطور,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...,https://sabbar.com/en/jobs/c-riyadh-r-sales-re...,Saudi Arabia,Hawtat Bani Tamim,ON_SITE,FULLTIME,None,0-1,None,None,5000,None,2025-11-23,None
14652,sabbar,Sales Representative,Deraah Perfumes | درعه للعطور,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...,https://sabbar.com/en/jobs/c-ad-diriyah-r-sale...,Saudi Arabia,Hawtat Bani Tamim,ON_SITE,FULLTIME,None,0-1,None,None,5000,None,2025-11-23,None
14653,sabbar,Sales Representative,Deraah Perfumes | درعه للعطور,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...,https://sabbar.com/en/jobs/c-al-kharj-r-sales-...,Saudi Arabia,Hawtat Bani Tamim,ON_SITE,FULLTIME,None,0-1,None,None,5000,None,2025-11-23,None
14654,sabbar,Sales Representative,Deraah Perfumes | درعه للعطور,نبحث عن ممثل مبيعات لبيع منتجات درعه في الفروع...,https://sabbar.com/en/jobs/c-hawtat-bani%20tam...,Saudi Arabia,Hawtat Bani Tamim,ON_SITE,FULLTIME,None,0-1,None,None,5000,None,2025-11-23,None

In [20]:
df_clean.to_csv("../data/interim/cleaned_sabbar.csv", index=False, encoding="utf-8-sig")
print("saved:", df_clean.shape)

saved: (14655, 17)

In [21]:
df_clean.to_json(
    "../data/interim/cleaned_sabbar.json",
    orient="records",
    force_ascii=False,
    indent=2,
)
print("saved json:", df_clean.shape)

saved json: (14655, 17)